"""The register's author lists are checked against the BibTeX beside them.

**Why this file exists.** On 14 September 2026 every DOI in `notes/references.md`
was re-negotiated and twenty-three entries were found wrong in thirty-one
fields: author lists belonging to other papers, wrong first authors, author
fields holding a journal name, silent truncations, ten wrong "and N others"
counts and seven wrong page ranges. `notes/decisions.md` records the audit. Two
of those defects had been found earlier, by accident, when a later pass happened
to need the same paper for something else.

**Why it can run offline.** `notes/references.bib` is generated by content
negotiation and committed beside the register, so it *is* the authoritative
record for every entry that has a DOI. Comparing the register's prose against it
needs no network and catches the whole class: if the prose and the negotiated
BibTeX disagree about who wrote a paper, the prose is wrong.

**What is deliberately not checked.** Seventeen entries appear in the
generator's `PROVENANCE` dict because the registry's own record cannot supply
their citation -- literal institutional authors, transposed or mis-cased deposit
fields, chapters for which Crossref returns no author list. Those are exempted
by name rather than by heuristic, because a check that fires on entries that are
fine is a check that gets turned off, which
`notes/grounding-methods.md` records as this project's own reasoning about
verification.
"""

from __future__ import annotations

import re
import sys
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from scripts.build_references_bib import (  # noqa: E402
    KEYS,
    PROVENANCE,
    REGISTER,
)

BIB = (REPO / "notes" / "references.bib").read_text(encoding="utf-8")
TEXT = REGISTER.read_text(encoding="utf-8")
LINES = TEXT.split("\n")

DOI_LINE = re.compile(r"^`(10\.\d{4,9}/[^`\s]+)`\s*—")

#: A truncation marker. "and others" and "et al." carry no count; "and 14
#: others" and "and fourteen others" do, and are the register's normal way of
#: abbreviating a long author list.
TRUNC_ANY = re.compile(r"\band\s+(?:\S+\s+)?others\b|\bet\s+al\.?\b", re.I)
TRUNC_COUNTED = re.compile(r"\band\s+(\d+|[a-z]+(?:-[a-z]+)?)\s+others\b", re.I)

#: A given-name field: initials, hyphenated or particled, with or without the
#: trailing period. Anything comma-separated that is *not* one of these is a
#: family name. Matching on this rather than on the family name is what makes
#: the walk below reliable: initials are short and regular, surnames are not.
GIVEN = re.compile(r"^(?:[A-ZÀ-Þ][a-zà-þ]{0,2}\.?|Md\.?|Jr\.?)"
                   r"(?:[\s-]?(?:[A-ZÀ-Þ][a-zà-þ]{0,2}\.?|Jr\.?"
                   r"|del|de|van|der|den))*$")

WORDS = {w: i for i, w in enumerate(
    "zero one two three four five six seven eight nine ten eleven twelve "
    "thirteen fourteen fifteen sixteen seventeen eighteen nineteen "
    "twenty".split())}

#: Below this many named authors, a truncation hides the names a reader needs to
#: identify the work. Three is the conventional minimum for an "et al." form and
#: is the threshold every legitimate entry in this register already clears.
MIN_NAMED = 3


def fold(s: str) -> str:
    s = unicodedata.normalize("NFKD", str(s)).replace("\xa0", " ")
    s = "".join(c for c in s if not unicodedata.combining(c))
    return re.sub(r"[^a-z]", "", s.lower())


def entries() -> list[dict]:
    """Every register entry as (doi, author head), by walking to the DOI line."""
    out = []
    for i, line in enumerate(LINES):
        m = DOI_LINE.match(line)
        if not m:
            continue
        j = i - 1
        while j >= 0 and LINES[j].strip() and not LINES[j].lstrip().startswith("**"):
            j -= 1
        if j < 0 or not LINES[j].lstrip().startswith("**"):
            out.append(dict(doi=m.group(1), head=None, line=i + 1))
            continue
        block = re.sub(r"\s+", " ", " ".join(LINES[j:i])).strip()
        hm = re.match(r"\*\*(.+?)\*\*", block)
        head = hm.group(1).strip() if hm else None
        yr = re.search(r"\((\d{4})\)\.?\s*$", head or "")
        out.append(dict(doi=m.group(1), line=i + 1,
                        head=head,
                        authors=(head[:yr.start()].strip().rstrip(".,").strip()
                                 if yr else None)))
    return out


def bib_authors(doi: str) -> list[str]:
    """Family names from the generated BibTeX, in order."""
    key = KEYS.get(doi) or KEYS.get(doi.lower())
    if key is None:
        for k, v in KEYS.items():
            if k.lower() == doi.lower():
                key = v
                break
    if key is None:
        return []
    m = re.search(r"@\w+\{" + re.escape(key) + r",(.*)", BIB)
    if not m:
        return []
    # One brace level deep, so a DataCite entry's `{{Literal Name}}` survives
    # and the field ends at its own closing brace. An alternation of following
    # field names does not work: BibTeX field order is not fixed, and an
    # earlier version of this walked past the author field into the next one.
    a = re.search(r"author\s*=\s*\{((?:[^{}]|\{[^{}]*\})*)\}", m.group(1), re.I)
    if not a:
        return []
    field = a.group(1)
    out = []
    for unit in re.split(r"\s+and\s+", field):
        unit = unit.strip().strip("{}").strip()
        if not unit:
            continue
        out.append(unit.split(",")[0].strip() if "," in unit else unit)
    return out


def named_surnames(authors: str) -> list[str]:
    """The surnames the register names, in order, before any truncation marker.

    Walks the comma-separated fields and consumes a given-name field after each
    family name. A regex over the whole string cannot do this: initials
    themselves look like `Family, Initial` pairs, so a findall double-counts
    every author with two initials, which an earlier version of this file did.
    """
    head = TRUNC_ANY.split(authors)[0].strip().rstrip(",").strip()
    toks = [re.sub(r"^and\s+", "", s).strip()
            for t in head.split(",") for s in re.split(r"\s+and\s+", t)]
    toks = [x for x in toks if x]
    out, i = [], 0
    while i < len(toks):
        out.append(toks[i].rstrip("."))
        i += 2 if i + 1 < len(toks) and GIVEN.match(toks[i + 1]) else 1
    return out


def named_count(authors: str) -> int:
    return len(named_surnames(authors))


EXEMPT = {d.lower() for d in PROVENANCE}
ROWS = [e for e in entries() if e.get("authors")]


# --------------------------------------------------------------------------
# 4a: truncation markers that hide what a citation is for
# --------------------------------------------------------------------------

def test_no_author_list_is_truncated_without_a_count():
    """"Zhong, and others" is the signature of a search-result citation.

    A counted truncation is a deliberate abbreviation of a long list and is used
    throughout this register. An *uncounted* one carries no information about
    how many authors were dropped, and every instance found in the audit was a
    citation assembled from a search result rather than from metadata.
    """
    bad = [f"{e['doi']} (line {e['line']}): {e['authors']!r}" for e in ROWS
           if TRUNC_ANY.search(e["authors"])
           and not TRUNC_COUNTED.search(e["authors"])]

    assert bad == [], "uncounted truncation markers:\n  " + "\n  ".join(bad)


def test_a_truncated_author_list_still_names_enough_authors():
    """A truncation must not hide the authors that identify the work."""
    bad = [f"{e['doi']} (line {e['line']}): names {named_count(e['authors'])}"
           for e in ROWS
           if TRUNC_ANY.search(e["authors"]) and named_count(e["authors"]) < MIN_NAMED]

    assert bad == [], (f"truncated to fewer than {MIN_NAMED} named authors:\n  "
                       + "\n  ".join(bad))


def test_every_entry_has_something_shaped_like_an_author_list():
    """Four entries had a journal name where the authors belong.

    The failure is invisible to a reader skimming the register, because
    "**Atmospheric Research 308, 107542 (2024).**" looks like a citation head.
    What it lacks is a `Family, Initials` unit, which every real author list has
    and no journal name does.
    """
    bad = [f"{e['doi']} (line {e['line']}): {e['authors']!r}" for e in ROWS
           if e["doi"].lower() not in EXEMPT
           and not named_surnames(e["authors"])]

    assert bad == [], "no author unit in the citation head:\n  " + "\n  ".join(bad)


# --------------------------------------------------------------------------
# the strongest check: the prose against the negotiated BibTeX
# --------------------------------------------------------------------------

def test_the_first_author_matches_the_negotiated_record():
    """Seven wrong first authors have now been found in this register.

    Six were caught before a commit during the urban pass; the seventh survived
    into a commit and was found by this audit. The BibTeX is generated from the
    DOI, so it is the authority, and the comparison is free.
    """
    bad = []
    for e in ROWS:
        if e["doi"].lower() in EXEMPT:
            continue
        bib = bib_authors(e["doi"])
        if not bib:
            continue
        names = named_surnames(e["authors"])
        if not names:
            continue
        surname = names[0]
        if fold(surname) and fold(surname) not in fold(bib[0]) \
           and fold(bib[0]) not in fold(surname):
            bad.append(f"{e['doi']} (line {e['line']}): register {surname!r} "
                       f"vs BibTeX {bib[0]!r}")

    assert bad == [], "first author disagrees:\n  " + "\n  ".join(bad)


def test_the_stated_author_count_matches_the_negotiated_record():
    """Ten "and N others" counts were wrong and no pass had checked one.

    This is the check that found the largest single class in the audit, and it
    needs nothing but the two committed files. Named authors plus the stated
    remainder must equal the number the registry returned.
    """
    bad = []
    for e in ROWS:
        if e["doi"].lower() in EXEMPT:
            continue
        bib = bib_authors(e["doi"])
        if not bib:
            continue
        if TRUNC_ANY.search(e["authors"]) and not TRUNC_COUNTED.search(e["authors"]):
            continue          # reported by the uncounted-truncation test above
        named = named_count(e["authors"])
        m = TRUNC_COUNTED.search(e["authors"])
        if m:
            tok = m.group(1).lower()
            stated = int(tok) if tok.isdigit() else WORDS.get(tok)
            if stated is None:
                bad.append(f"{e['doi']} (line {e['line']}): unreadable count "
                           f"{tok!r}")
                continue
            total = named + stated
        else:
            total = named
        if total != len(bib):
            bad.append(f"{e['doi']} (line {e['line']}): register accounts for "
                       f"{total}, BibTeX has {len(bib)}")

    assert bad == [], "author count disagrees:\n  " + "\n  ".join(bad)


# --------------------------------------------------------------------------
# a cheap structural check that caught nothing, kept because it costs nothing
# --------------------------------------------------------------------------

def test_page_ranges_run_forwards():
    """Seven page ranges were wrong and every one was still ordered.

    So this check would have caught none of them, and it is kept anyway because
    it is free and guards a different mistake -- a transposed range -- that the
    register has not yet made. It is recorded as having caught nothing so that
    its value is not overstated.
    """
    bad = []
    for m in re.finditer(r"\*\s+\d+,\s*(\d+)[-–](\d+)\.", TEXT):
        first, second = int(m.group(1)), int(m.group(2))
        if second <= first:
            bad.append(m.group(0))

    assert bad == [], f"page ranges that do not run forwards: {bad}"


# --------------------------------------------------------------------------
# the guards have to actually catch the defects they were written for
# --------------------------------------------------------------------------
# `tests/test_prose_claims.py` establishes the convention: a check that passes
# because it found nothing is indistinguishable from one that works. Each of the
# four defects below is a real one this audit found, reconstructed from the
# register as it stood at 668ef80.

def test_the_guard_catches_an_uncounted_truncation():
    """The Zhong defect: "Zhong, and others" with no count and one name."""
    head = "Zhong, and others"

    assert TRUNC_ANY.search(head)
    assert not TRUNC_COUNTED.search(head)
    assert named_count(head) < MIN_NAMED


def test_the_guard_catches_a_journal_in_the_author_slot():
    """Four entries had a journal name where the author list belongs."""
    for head in ("Atmospheric Research 308, 107542",
                 "Scientific Reports 15",
                 "Earth System Science Data 18, 4279–4301"):
        assert named_surnames(head) == [] or not re.search(
            r"[A-ZÀ-Þ][a-zà-þ]+,\s*[A-ZÀ-Þ]\.", head), head


def test_the_guard_catches_a_wrong_stated_count():
    """"and 21 others" after ten names, for a thirteen-author paper."""
    head = ("Ploton, P., Mortier, F., Réjou-Méchain, M., Barbier, N., "
            "Picard, N., Rossi, V., Dormann, C., Cornu, G., Viennois, G., "
            "Bayol, N., and 21 others")
    m = TRUNC_COUNTED.search(head)

    assert m and named_count(head) + int(m.group(1)) != 13


def test_the_guard_catches_a_wrong_first_author():
    """The MultiTab preprint was entered as Kim where the paper is Lee."""
    head = "Kim, K., Lee, J., and 4 others"

    assert named_surnames(head)[0] == "Kim"
    assert fold("Kim") not in fold("Lee")


def test_the_surname_walk_counts_two_initial_authors_once():
    """The bug an earlier version of this file had, pinned so it cannot return.

    A findall of `Family, Initial` double-counts every author written with two
    initials, because "D. J., Maasakkers" matches the same shape as
    "Jacob, D." That made the count check report a spurious disagreement on
    about a fifth of the register.
    """
    head = "Sheng, J.-X., Jacob, D. J., Maasakkers, J. D., Zhang, Y."

    assert named_surnames(head) == ["Sheng", "Jacob", "Maasakkers", "Zhang"]
